In [1]:
import numpy as np

COPY and View in array

Copy : makes a copy of original array , changes made in the copy array does not affect og array.

View : View is a representation or projection of orginal array, any changes made in the array will affect the original array.

In [2]:
import numpy as np

ar = np.array([[1,2],[4,5]])

copy=ar.copy()
copy[0][0]=42
print(ar) 
print(copy)

[[1 2]
 [4 5]]
[[42  2]
 [ 4  5]]


In [34]:
arr = np.array([[[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]]])
print (arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [35]:
print(arr.ndim)
print(ar.ndim)

3
2


In [36]:
#higher dimensional array

arr = np.array([1,2,3,4], ndmin=1)

print(arr)
print('number of dimension: ' ,arr.ndim )

[1 2 3 4]
number of dimension:  1


In [37]:
arr1 = np.array([[1,2,3],[9,8,7]])

print (arr1[1,1])

print (arr[0]+arr[2])

8
4


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [39]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


### NumPy Datatypes

In [40]:
#check datatype of array

arr = np.array([1,2,3,4])

print(arr.dtype)

int32


In [41]:
#check datatype

arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


creating array with defined datatypes

In [42]:
arr = np.array({1,2,3,4}, dtype = 'S')

print (arr)
print (arr.dtype)

b'{1, 2, 3, 4}'
|S12


In [11]:
arr = np.array([[[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]]])
print (arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
print(arr.ndim)
print(ar.ndim)

3
2


In [30]:
#higher dimensional array

arr = np.array([1,2,3,4], ndmin=1)

print(arr)
print('number of dimension: ' ,arr.ndim )

[1 2 3 4]
number of dimension:  1


In [31]:
arr1 = np.array([[1,2,3],[9,8,7]])

print (arr1[1,1])

print (arr[0]+arr[2])

8
4


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [49]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


### NumPy Datatypes

In [3]:
#check datatype of array

arr = np.array([1,2,3,4])

print(arr.dtype)

int32


In [4]:
#check datatype

arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


creating array with defined datatypes

In [5]:
arr = np.array({1,2,3,4}, dtype = 'S')

print (arr)
print (arr.dtype)

b'{1, 2, 3, 4}'
|S12


Converting datatypes on existing arrays

In [19]:
arr = np.array([122.1, 222.1, 322.1])

newarr = arr.astype('int32')

print(newarr)
print(newarr.dtype)

[122 222 322]
int32


In [22]:
arr = np.array([1,0,3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)


[ True False  True]
bool


NumPy array COPY vs VIEW

Copy is making a new copy of the original array and View is represesntaion of original array

Any change made to the copy will not affect the og array and viceversa
any changes made to view will affect the og array and viceversa.

In [24]:
arr = np.array([1,2,3,4,5,6])

x = arr.copy()
arr[0] = 42
x[0]=99
print(arr)
print(x)

[42  2  3  4  5  6]
[99  2  3  4  5  6]


In [28]:
arr = np.array([1,2,3,4,5,6,7]) 
x = arr.view()
arr[0] = 42
print(arr)
print(x)

x[0]=1
print(arr)

[42  2  3  4  5  6  7]
[42  2  3  4  5  6  7]
[1 2 3 4 5 6 7]


Check if array owns its data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
numpy array has attribute 'base' that returns 'none' if the array owns data
otherwise it refers to original object 

In [29]:

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


SHAPE of an ARRAY

THE NUMBER OF ELEMENT IN EACH DIMENSION IS SHAPE OF AN ARRAY

In [41]:
arr = np.array([[1,2,3],[4,5,6]], ndmin = 5)


print (len(arr.shape))
print(arr.shape)
print(arr)


5
(1, 1, 1, 2, 3)
[[[[[1 2 3]
    [4 5 6]]]]]


In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

newarr = arr.reshape(3,4)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2,-1)    #[ [  [ 1234 ]  ] ]       [ [   [ 1234 ]  ] ]

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
##flattening the array

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


Iterating in numPy

In [19]:
arr = np.array([1,2,3,4,5])

for x in arr :
    print (x)

1
2
3
4
5


In [21]:
arr  = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [27]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)

for x in arr:
    print(x)

3
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


Iterating array wih different datatypes

We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

If we wnt to do changes while iterating then we have to use np.nditer

In [29]:
arr = np.array ([1,2,3])

for x in np.nditer(arr, flags = ['buffered'], op_dtypes=['S']):
    print (x)

b'1'
b'2'
b'3'


In [30]:
#we can iterate with different step size

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [31]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


Append aaray


In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)

print (arr)

newarr = np.append (arr, [7,8,9])

print (newarr)

(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


If you are adding row then use axis  = 0 and if you are adding column axis = 1

In [7]:

newarr = np.append (arr, [[7,8,9]], axis = 0)
print (newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
newarr = np.append (arr, [[7],[8]], axis = 1)
print (newarr)

[[1 2 3 7]
 [4 5 6 8]]


In [19]:
#Insert Method

arr = np.array([[1,2],[3,4],[5,6]])
print(arr)

np.insert(arr,3,[11,12])


[[1 2]
 [3 4]
 [5 6]]


array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [20]:
np.insert(arr,1,[11,12],axis = 0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [22]:
np.insert(arr,1,[11,12,13],axis = 1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [35]:
a = np.array([[1,2,3,12],[9,5,6,11],[8,4,10,7]])

np.delete(a,4)


array([ 1,  2,  3, 12,  5,  6, 11,  8,  4, 10,  7])

In [37]:
np.delete(a,1,axis = 0)

array([[ 1,  2,  3, 12],
       [ 8,  4, 10,  7]])

In [38]:
np.delete(a,1,axis = 1)

array([[ 1,  3, 12],
       [ 9,  6, 11],
       [ 8, 10,  7]])

DIMENSIONS IN ARRAY

In [40]:
A =np.array(5)

np.ndim(A)   # ndim to show dimension of array

0

In [44]:
one = np.array([1,2,3,4,5])
two = np.array([[1,2,3],[4,5,6]])
three = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [49]:
print (three)
three.shape  ### to get the arrangement 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [51]:
print(np.ndim(one))
print(np.ndim(two))
print(np.ndim(three))

1
2
3


DIFFERENCE BETWEEN LIST AND ARRAY

LIST :
 We can use any datatypein list.

ARRAY :
We have to maintain singular datatype.

In [53]:
#Type conversion can happen in array
arr = np.array([1,2,3,'apple']) 
arr

array(['1', '2', '3', 'apple'], dtype='<U11')

In [26]:
#Allows Mathematical Operations 

arr = np.array([1,2,3,4,5,6])
print(arr/5)

list = [1,2,3,4]
print(list/5)

[0.2 0.4 0.6 0.8 1.  1.2]


TypeError: unsupported operand type(s) for /: 'list' and 'int'

Arrays consumes less memory.
Array are faster than lists

ARRAY RESHAPING

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1d array

newarr = arr.reshape(2,6)

newarr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
newarr = arr.reshape(2,3,2)   #(x,y,z) : x=matrix , y= rows , z= cols

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


ARRAY INDEXING

In [16]:
arr = np.array([1,2,3,4])
print(arr[3])
print(arr[1]+arr[2])

4
5


In [15]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)
print(arr[0,3])
print(arr[1,3])

(2, 5)
4
9


In [20]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.shape)
print(arr)
print(arr[0,0,2])
print(arr[1,1,1])


(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
11


Hstack and Vstack

Hstack is use when joining array horizontally.

Vstack is used when its for joing vertically

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [22]:
print(a,b)
print(np.ndim(a),np.ndim(b))

[1 2 3] [4 5 6]
1 1


In [25]:
#Performing Hstack

resulth = np.hstack((a,b))
print(resulth)
print(np.ndim(resulth))

[1 2 3 4 5 6]
1


In [24]:
#perform vstack

resultv = np.vstack((a,b))
print(resultv)
print(np.ndim(resultv))

[[1 2 3]
 [4 5 6]]
2


### NumPy Concontenation

Used to join 2 or more array of same shape aloong specified axis.

AXIS = 0,adding new rows,

Axis = 1,adding new columns

In [28]:
arr1 = np.array([[2,4],[6,8]])
arr2 = np.array([[3,5],[7,9]])

arr3 =np.array([[3],[9]])
arr4 =np.array([[4],[8]])

new = np.concatenate((arr1,arr2),axis = 0)
print(new)

new1 = np.concatenate((arr1,arr2),axis = 1)
print(new1)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]
[[2 4 3 5]
 [6 8 7 9]]


In [32]:
print(arr3.shape,arr4.shape)

new2 =  np.concatenate((arr3,arr4),axis = 1)
print(new2,new2.shape)

(2, 1) (2, 1)
[[3 4]
 [9 8]] (2, 2)
